# Generated by Django 6.0.6 on 2026-06-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='atualizado_em',
            field=models.DateField(auto_now=True),
        ),
    ]
