# Generated by Django 6.0.6 on 2026-06-15 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_userlocation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLocation',
        ),
    ]
