# Generated by Django 6.0.6 on 2026-06-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_delete_userlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
