# Generated by Django 6.0.6 on 2026-06-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_disponibilidade_atualizado_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidade',
            name='atualizado_em',
            field=models.DateField(auto_now=True),
        ),
    ]
